version: "3"

services:
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      TZ: "America/Sao_Paulo"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/data:/var/lib/postgresql/data
    ports:
      - 5434:5432
    networks:
      - the_net

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db
    networks:
      - the_net

networks:
  the_net:
    driver: bridge
